services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itsumoarigatone
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
volumes:
  postgres-data:
  minio-data: